apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nodejs-cicd-api
  description: "API for CI/CD Pipeline"
spec:
  type: openapi
  lifecycle: production
  owner: group:ultracloud5652
  definition: |
    openapi: 3.0.0
    info:
      title: Node.js CI/CD API
      version: 1.0.0
