apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nodejs-cicd-pipeline
  description: A CI/CD pipeline for a Node.js app, deploying to AWS ECS using GitHub Actions.
  annotations:
    github.com/project-slug: ultracloud5652/nodejs-cicd-pipeline
    github.com/workflows: nodejs-ci.yml
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:default/ultracloud5652
  system: system:default/cicd-pipelines
  providesApis:
    - api:default/nodejs-cicd-api
